### ISSUE TITLE
twitch irc chat server info parsing

### ISSUE THREAD

**Issue by Tillerino** [RedbackThomson/OsuCelebrity#9]
When connecting to the twitch IRC server, we get the following error:

```
ERROR org.pircbotx.PircBotX  - Exception encountered when parsing line
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.pircbotx.ServerInfo.parse004(ServerInfo.java:113)
	at org.pircbotx.ServerInfo.parse(ServerInfo.java:106)
	at org.pircbotx.InputParser.processServerResponse(InputParser.java:709)
	at org.pircbotx.InputParser.handleLine(InputParser.java:323)
	at org.pircbotx.PircBotX.startLineProcessing(PircBotX.java:275)
	at org.pircbotx.PircBotX.connect(PircBotX.java:236)
	at org.pircbotx.PircBotX.startBot(PircBotX.java:151)
	at me.reddev.osucelebrity.twitch.TwitchIrcBot.run(TwitchIrcBot.java:97)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Apparently when sending the server info 004 (ref: https://www.alien.net.au/irc/irc2numerics.html), the twitch IRC server sends _nothing_, just an empty line. Maybe we're doing something wrong, maybe the server is weird.

**Comment by Tillerino** [comment]
Implemented a workaround in pircbotx 2.0.1, available here:
https://github.com/Tillerino/pircbotx/tree/2.0.1
